### PR TITLE
rticonnextdds-connector library changes and version string changes for release 1.2.2

### PR DESCRIPTION
**Pull request by alvinkrebs**
Changed references in rticonnextdds-connector to latest develop branch changes in rticonnextdds-connector repository.
Changed version string to 1.2.2

### CODE REVIEW

**Review by samuelraeburn — CHANGES_REQUESTED** [review]
We need to target the support branch, not the release branch

**Comment by alvinkrebs** [comment]
> 

We are creating support/connector/1.2.2? Is the upstream branch still master?

**Comment by samuelraeburn** [comment]
@alexcamposruiz Can correct me if I'm wrong but AFAIK the branching scheme is:

* `develop` used for active development of next release
* `master` contains latest release (which in this case will be 1.2.2)
* `release/connector/1.2.0` contains 1.2.0 release
* `support/connector/1.2.0` is branched off of `release/connector/1.2.0`, used for patches of that version (such as 1.2.2)
So in this case, these changes should be made in `support/connector/1.2.0` and then one all of the changes for the 1.2.2 release are in that branch we will create the `release/connector/1.2.2` branch.

**Comment by alvinkrebs** [comment]
This PR is targeting the wrong branch. Closing.

**Pull request closed without merging**
