### PR TITLE
IRONSIDE-1166, merge release/connector/1.3.0 to master via feature branch

### PR DESCRIPTION
**Pull request by alvinkrebs**
Merge release 1.3.0 to master via this release branch.

1. Several modifications to the rticonnextdds-connector. The largest being we no longer commit libraries. So, you'll see the lib/ directory disappear in the rticonnector-connector subrepository/folder.
2. Supporting this change are various configuration changes and new scripts. README and LICENSE were also adjusted.
3. This merge through a feature branch is necessary as there is one change ci_config.yaml. We don't want to change release/connector/1.3.0 and we don't need a new commit to master.

This branch is sourced from master and will be merged back to master once the change to ci_config.yaml has been updated.

### CODE REVIEW

**Review by elainerti — COMMENTED** [review]
Validation failed. We should fix that before we can say this merge is fine.

**Comment by ManuelJNunez** [comment]
Why are the reviewing the merge from release into a feature branch? You should create a feature branch from master and then merge release into that branch. Then you should open a PR from the feature branch to master.

**Comment by alvinkrebs** [comment]
The idea here is to make the suggested changes to ci_config.yaml after this PR is approved but prior to merging to master. That way, we can stop here and see if our CI completes, then move on. Also, this does not need a change in release/connector/1.3.0, we can keep that branch clean.

**Comment by ManuelJNunez** [comment]
> The idea here is to make the suggested changes to ci_config.yaml after this PR is approved but prior to merging to master. That way, we can stop here and see if our CI completes, then move on. Also, this does not need a change in release/connector/1.3.0, we can keep that branch clean.

You can make the changes on the feature branch before merging to master.

**Pull request closed without merging**
