### PR TITLE
Set rticonnector version string to 1.2.0

### PR DESCRIPTION
**Pull request by alvinkrebs**
Bamboo tests are failing because 1.2.0.rc1 rticonnector doesn't exist.

### CODE REVIEW

**Comment by samuelraeburn** [comment]
Wasn't all of this already done here: https://github.com/rticommunity/rticonnextdds-connector-js/pull/81/files ?

**Comment by samuelraeburn** [comment]
I think your local release branch is out of date. All you should need to do is create a branch off of release/connector/1.2.0 (after pulling in any changes) and then change the 1.2.0.rc1 to 1.2.0-rc1

**Comment by samuelraeburn** [comment]
This can be closed, right?

**Comment by alvinkrebs** [comment]
Cancelling this PR, version string was wrong

**Pull request closed without merging**
